### ISSUE TITLE
mac上配置好环境以后直接执行python notion_backup_terminal.py报错

### ISSUE THREAD

**Issue by marsjane** [delta1037/notion-export-client#10]
Traceback (most recent call last):
  File "notion_backup_terminal.py", line 9, in <module>
    from NotionDump import NotionBackupLogger
ImportError: cannot import name 'NotionBackupLogger' from 'NotionDump' (/opt/homebrew/anaconda3/envs/notion/lib/python3.7/site-packages/NotionDump/__init__.py)

**Comment by peylnog** [comment]
+1 the same problem

**Comment by delta1037** [comment]
原因：最新的一次更新忘记推送到PyPI上了。
解决：将kernel版本更新到0.2.3版本即可。
