### ISSUE TITLE
多个页面备份配合Windows定时程序每天自动备份不能完全自动化

### ISSUE THREAD

**Issue by Lion066** [delta1037/notion-export-client#12]
Notion备份模版里的备份清单是根据 备份的勾选情况来备份的，如果要每天自动运行备份的话，还有一个问题，就是得 每天勾选一下要备份的页面，如果备份完成，不去掉 备份清单里的 √，是不是就没有这个小麻烦了？

**Comment by delta1037** [comment]
done at v3.0.1
