### ISSUE TITLE
Terninal版本能否后台运行，实现无感备份？

### ISSUE THREAD

**Issue by Lion066** [delta1037/notion-export-client#14]
我每天使用windows定时任务运行备份程序，目前的terminal 版本运行的时候会有一个窗口，因为我是每天定时备份，我希望这个备份程序后台自动运行，不要在前台出现窗口，避免干扰。
我目前自己的解决办法是用了一个VBS脚本，把备份程序后台运行，基本也能满足我的需求，如果terminal 版本能够完善一下这点就更好了，这个备份程序很好用，完美解决notion云端笔记焦虑，给作者点赞👍🏻

**Comment by delta1037** [comment]
done at v3.0.1
