### ISSUE TITLE
备份database时报错

### ISSUE THREAD

**Issue by Lackel** [delta1037/notion-export-client#9]
大佬，请问我在使用您的工具进行备份时，其他页面和database都备份正常，只有一个database报如下错误，请问该如何解决？
![7(G}LX}QPJ 0 DU9`6TG$T](https://user-images.githubusercontent.com/39994881/229069238-8c011e14-700d-4259-95ab-87c5970e3bf2.png)

**Comment by delta1037** [comment]
难道是新版本的Notion修改了数据库的json格式？可以提供一个出错的数据库样例吗？
